<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Str;

class InvoiceSetting extends Model
{
    protected $fillable = [
        'slug',
        'repeat_every_date',
        'due_date_after',
        'cancel_after',
    ];

    protected function casts(): array
    {
        return [
            'slug' => 'string',
        ];
    }

    protected static function boot(): void
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::creating(function (InvoiceSetting $invoiceSetting) {
            $invoiceSetting->slug = Str::uuid()->toString();
        });
    }

    public function getRouteKeyName(): string
    {
        return 'slug';
    }
}
