<?php

namespace App\Filament\Resources\CustomerServiceResource\Pages;

use App\Enums\AccountType;
use App\Enums\PackageTypeService;
use App\Filament\Resources\CustomerServiceResource;
use App\Filament\Resources\UserResource\Pages\ViewUser;
use App\Models\CustomerService;
use Filament\Infolists\Components\Group;
use Filament\Infolists\Components\Section;
use Filament\Infolists\Components\TextEntry;
use Filament\Infolists\Infolist;
use Filament\Resources\Pages\ViewRecord;

class ViewCustomerService extends ViewRecord
{
    protected static string $resource = CustomerServiceResource::class;
    protected static ?string $title = 'Detail';

    public function infolist(Infolist $infolist): Infolist
    {
        parent::infolist($infolist); // TODO: Change the autogenerated stub

        return $infolist
            ->columns(3)
            ->schema([
                Group::make()
                    ->schema([
                        Section::make('Data Pelanggan')
                            ->inlineLabel()
                            ->schema([
                                TextEntry::make('user.name')
                                    ->label('Nama Pelanggan')
                                    ->color('primary')
                                    ->url(fn(CustomerService $record): string => ViewUser::getUrl(['record' => $record->user?->username])),

                                TextEntry::make('user.userProfile.account_type')
                                    ->label('Tipe')
                                    ->formatStateUsing(fn($state): string => AccountType::tryFrom($state)?->getLabel() ?? '-'),

                                TextEntry::make('user.userProfile.place_name')
                                    ->label('Tempat Usaha'),

                                TextEntry::make('user.userProfile.whatsapp_number')
                                    ->label('No. WhatsApp'),
                            ]),

                        Section::make('Data Paket')
                            ->inlineLabel()
                            ->schema([
                                TextEntry::make('reference_number')
                                    ->label('Nomor Referensi'),

                                TextEntry::make('servicePackage.package_name')
                                    ->label('Paket'),

                                TextEntry::make('package_type')
                                    ->label('Jenis Paket')
                                    ->formatStateUsing(fn($state): string => PackageTypeService::tryFrom($state)?->getLabel() ?? '-'),
                            ]),
                    ])
                    ->columnSpan(['lg' => 2]),

                Group::make()
                    ->schema([
                        Section::make()
                            ->schema([

                            ]),
                    ])
                    ->columnSpan(['lg' => 1]),
            ]);
    }
}
