<?php

namespace App\Filament\Resources\UserResource\Pages;

use App\Filament\Resources\UserResource\Schemas\UserInfoList;
use App\Filament\Resources\UserResource\UserResource;
use Filament\Infolists\Infolist;
use Filament\Resources\Pages\ViewRecord;

class ViewUser extends ViewRecord
{
    protected static string $resource = UserResource::class;

    protected static ?string $title = 'Detail';

    public function infolist(Infolist $infolist): Infolist
    {
        parent::infolist($infolist); // TODO: Change the autogenerated stub

        return UserInfoList::configure($infolist);
    }
}
